version: '3.1'
services:
  stats-server:
    build: ./stats/service
    image: stats-service
    container_name: statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./main
    image: main-service
    container_name: mainServer
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmdb
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
